server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        namespace: ticket
    gateway:
      default-filters:
        - AddRequestHeader=key,value
      routes:
        - id: user # 路由规则id，自定义，唯一
          uri: lb://user-service # 路由的目标服务，lb代表负载均衡，会从注册中心拉取服务列表
          predicates: # 路由断言，判断当前请求是否符合当前规则，符合则路由到目标服务
            - Path=/api/users/** #这里是以请求路径作为判断规则
        - id: film # 路由规则id，自定义，唯一
          uri: lb://film-service # 路由的目标服务，lb代表负载均衡，会从注册中心拉取服务列表
          predicates: # 路由断言，判断当前请求是否符合当前规则，符合则路由到目标服务
            - Path=/api/films/** #这里是以请求路径作为判断规则
        - id: trade # 路由规则id，自定义，唯一
          uri: lb://trade-service # 路由的目标服务，lb代表负载均衡，会从注册中心拉取服务列表
          predicates: # 路由断言，判断当前请求是否符合当前规则，符合则路由到目标服务
            - Path=/api/trade/** #这里是以请求路径作为判断规则
        - id: session # 路由规则id，自定义，唯一
          uri: lb://sessions-service # 路由的目标服务，lb代表负载均衡，会从注册中心拉取服务列表
          predicates: # 路由断言，判断当前请求是否符合当前规则，符合则路由到目标服务
            - Path=/api/hall/**, /api/seats/**, /api/sessions/** #这里是以请求路径作为判断规则

auth:
  jwt:
    secret: secretsecretsecretsecretsecretsecretsecretsecretsecret
    header: Authorization # JWT存储的请求头
    expiration: 604800000 # JWT的超期时间，这里是7天
    excludePaths: # 无需登录校验的路径
      - /api/users/login
      - /api/users/add
      - /api/films/list